# Generated by Django 3.1.2 on 2020-10-24 22:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('pay', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('O', 'open'), ('C', 'close'), ('D', 'delete')], default='O', max_length=1)),
                ('publishTime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 22, 30, 44, 89958, tzinfo=utc))),
                ('modifiedTime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 22, 30, 44, 273209, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=20, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200, unique=True)),
                ('displayName', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True, default='')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('', 'None')], default='', max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(blank=True, max_length=20)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('lineId', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MiddleAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.case')),
                ('hashtag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.hashtag')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='employerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.user'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='')),
                ('accepted', models.CharField(blank=True, choices=[('A', 'accept'), ('R', 'reject'), ('T', 'TBC')], default='T', max_length=1)),
                ('employerRating', models.FloatField(blank=True, default=None, null=True)),
                ('employeeRating', models.FloatField(blank=True, default=None, null=True)),
                ('caseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.case')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.user')),
            ],
        ),
    ]
