# Generated by Django 3.1.2 on 2020-10-20 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200, unique=True)),
                ('displayName', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('gender', models.CharField(max_length=1)),
                ('birthday', models.DateTimeField()),
                ('phone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('caseId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('pay', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('publishTime', models.DateTimeField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='works.user')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField()),
                ('caseId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='works.case')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='works.user')),
            ],
        ),
    ]
