# Generated by Django 3.1.2 on 2020-10-22 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='modifiedTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 5, 54, 42, 726134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='case',
            name='publishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 5, 54, 42, 542584, tzinfo=utc)),
        ),
    ]
