# Generated by Django 3.1.2 on 2020-10-22 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20201022_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accepted',
            field=models.CharField(blank=True, choices=[('A', 'accept'), ('R', 'reject'), ('T', 'TBC')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='case',
            name='modifiedTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 6, 34, 29, 475474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='case',
            name='publishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 6, 34, 29, 290258, tzinfo=utc)),
        ),
    ]
