# Generated by Django 3.1.2 on 2020-10-23 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20201022_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='caseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='modifiedTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 16, 42, 55, 887135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='case',
            name='publishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 16, 42, 55, 698161, tzinfo=utc)),
        ),
    ]
