# Generated by Django 3.1.2 on 2020-10-24 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20201024_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.user'),
        ),
        migrations.AlterField(
            model_name='case',
            name='employerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.user'),
        ),
        migrations.AlterField(
            model_name='case',
            name='modifiedTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 14, 14, 21, 397277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='case',
            name='publishTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 14, 14, 21, 210972, tzinfo=utc)),
        ),
    ]
