# Generated by Django 3.1.2 on 2020-10-24 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20201024_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='modifiedTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 15, 15, 36, 795138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='case',
            name='pay',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='publishTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 15, 15, 36, 605740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='case',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='displayName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='MiddleAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseHashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.case')),
            ],
        ),
    ]
