# Generated by Django 3.1.2 on 2020-10-24 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20201024_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='middleagent',
            name='caseHashtag',
        ),
        migrations.AddField(
            model_name='middleagent',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.case'),
        ),
        migrations.AddField(
            model_name='middleagent',
            name='hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.hashtag'),
        ),
        migrations.AlterField(
            model_name='case',
            name='modifiedTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 15, 27, 32, 973125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='case',
            name='publishTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 15, 27, 32, 785327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
