# Generated by Django 3.1.2 on 2020-10-24 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20201024_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='modifiedTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 16, 39, 59, 878280, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='case',
            name='publishTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 24, 16, 39, 59, 695185, tzinfo=utc)),
        ),
    ]
